create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  price numeric not null default 0 check (price >= 0),
  calo numeric not null default 0 check (calo >= 0),
  moods jsonb not null default '[]'::jsonb,
  budget text not null default 'all',
  category text not null default 'all',
  tags jsonb not null default '[]'::jsonb,
  img text not null default '',
  popular boolean not null default false,
  rating numeric not null default 0,
  time text not null default '',
  type text not null default 'man',
  diet text not null default 'man'
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  dish_id bigint not null references public.dishes (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, dish_id)
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  dish_id bigint not null references public.dishes (id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create index if not exists history_user_viewed_at_idx
  on public.history (user_id, viewed_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.create_profile_for_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.email, '')
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute function public.create_profile_for_auth_user();

insert into public.profiles (id, name, email)
select id, coalesce(raw_user_meta_data ->> 'name', ''), coalesce(email, '')
from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.admin_update_profile(
  target_user_id uuid,
  new_name text default null,
  new_role text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  updated_profile public.profiles;
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  if new_role is not null and new_role not in ('customer', 'admin') then
    raise exception 'Invalid role' using errcode = '22023';
  end if;

  if new_role = 'customer' and exists (
    select 1 from public.profiles
    where id = target_user_id and role = 'admin'
  ) and (select count(*) from public.profiles where role = 'admin') <= 1 then
    raise exception 'Cannot demote the last admin' using errcode = '23514';
  end if;

  update public.profiles
  set name = coalesce(nullif(btrim(new_name), ''), name),
      role = coalesce(new_role, role)
  where id = target_user_id
  returning * into updated_profile;

  if not found then
    raise exception 'User not found' using errcode = 'P0002';
  end if;
  return updated_profile;
end;
$$;

revoke all on function public.admin_update_profile(uuid, text, text) from public;
grant execute on function public.admin_update_profile(uuid, text, text) to authenticated;

create or replace function public.replace_my_favorites(dish_ids bigint[])
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  delete from public.favorites where user_id = (select auth.uid());
  insert into public.favorites (user_id, dish_id)
  select (select auth.uid()), requested_id
  from (
    select distinct unnest(coalesce(dish_ids, '{}'::bigint[])) as requested_id
  ) requested
  where exists (select 1 from public.dishes where id = requested_id);
end;
$$;

revoke all on function public.replace_my_favorites(bigint[]) from public;
grant execute on function public.replace_my_favorites(bigint[]) to authenticated;

alter table public.profiles enable row level security;
alter table public.dishes enable row level security;
alter table public.favorites enable row level security;
alter table public.history enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.dishes from anon, authenticated;
revoke all on public.favorites from anon, authenticated;
revoke all on public.history from anon, authenticated;

drop policy if exists "Users can read own profile and admins can read all" on public.profiles;
create policy "Users can read own profile and admins can read all"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists "Users can update own profile name" on public.profiles;
create policy "Users can update own profile name"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

drop policy if exists "Anyone can read dishes" on public.dishes;
create policy "Anyone can read dishes"
  on public.dishes for select to anon, authenticated
  using (true);

drop policy if exists "Admins can manage dishes" on public.dishes;
create policy "Admins can manage dishes"
  on public.dishes for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

drop policy if exists "Users can manage own favorites" on public.favorites;
create policy "Users can manage own favorites"
  on public.favorites for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "Users can manage own history" on public.history;
create policy "Users can manage own history"
  on public.history for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

grant select on public.profiles to authenticated;
grant update (name) on public.profiles to authenticated;
grant select on public.dishes to anon, authenticated;
grant insert, update, delete on public.dishes to authenticated;
grant select, insert, update, delete on public.favorites to authenticated;
grant select, insert, update, delete on public.history to authenticated;
grant usage, select on all sequences in schema public to authenticated;
